### ISSUE TITLE
getting window not defined error

### ISSUE THREAD

**Issue by abhinaba1080** [baruchvlz/resq#42]
hi,
I am getting window not defined error while importing the resq module. I am doing nothing fancy, just running:

```
import { resq$ } from 'resq';

console.log(resq$('MyComponent', null));
```
npm script: ts-node test.ts

Error thrown:

```
ReferenceError: window is not defined
    at Object.<anonymous> (C:\Dev Room\Projects\node_modules\resq\dist\index.js:1:221)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Dev Room\Projects\test.ts:3:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

**Comment by baruchvlz** [comment]
This seems to be an issue with your test configuration. Which testing framework or library are you using?

**Comment by abhinaba1080** [comment]
I am using protractor. browser: true can't be set at protractor configuration. 

Do you have any guidance/working example for protractor resq integration?

**Comment by baruchvlz** [comment]
> Do you have any guidance/working example for protractor resq integration?

My only recommendation would be to use something else. Protractor was built to test AngularJS (which is no longer supported by the Angular team) appliciations. Try using something like [WebdriverIO](http://webdriver.io) which uses this library internally to select React components.
